task_defaults:
  max_trials: 1
  aggregate_state: satisfy-last
  git_options: { submodules: { include_match: ^.*$ } }
  traits:
    Ansible 2: yes
    git-crypt: yes
    g2016: true # only faster machines

  environment_variables:
    LANG: "en_US.UTF-8"
    ANSIBLE_SSH_ARGS: '-i ~/.ssh/zhdk_ci_executor_rsa -o "UserKnownHostsFile ../../hosts-known-ssh-pubkeys"'
    ANSIBLE_STDOUT_CALLBACK: 'debug'
