# working example configuration to deploy a leihs instance using Cider-CI

jobs:
  deploy_leihs:
    name: Deploy Leihs Demo

    run_when:
      nightly:
        type: cron
        value: '0 2 * * *' # 2am UTC === 1am or 2am in Zurich (Summer/Winter)
        branch_include_match: ^master$
        rerun: true

    context:
      task_defaults:
        max_trials: 1
        aggregate_state: satisfy-last
        git_options: { submodules: { include_match: ^.*$ } }
        traits:
          Ansible 2: yes
          git-crypt: yes

        environment_variables:
          LEIHS_RELEASE_CHANNEL: 'mk/fix-demo-dump' # FIXME: use 'stable'
          LANG: "en_US.UTF-8"
          ANSIBLE_SSH_ARGS: '-i ~/.ssh/zhdk_ci_executor_rsa -o "UserKnownHostsFile ../../hosts-known-ssh-pubkeys"'
          ANSIBLE_STDOUT_CALLBACK: 'debug'

      tasks:
        deploy:
          exclusive_global_resources:
            "demo.leihs.zhdk.ch": true

          scripts:
            check-head-of-master:
              body: git fetch && test $(git log -n 1 --pretty=%H HEAD -- ) == $(git log -n 1 --pretty=%H origin/master -- )

            # unlock:
            #   body: git crypt unlock && ls -la . && ls -R group_vars

            deploy:
              start_when:
                # git-crypt is unlocked: {script_key: unlock}
                only when we are on the head of master branch: {script_key: check-head-of-master}
              timeout: 30 minutes
              body: |
                ./scripts/update_leihs_latest "$LEIHS_RELEASE_CHANNEL" && \
                ./scripts/deploy && \
                ./scripts/restore-from-backup && \
                echo OK

            # certbot:
            #   start_when: {after: {script_key: deploy}}
            #   body: |
            #     ssh "$LEIHS_INTERNAL_HOSTNAME" 'certbot run --apache -n --redirect --hsts --uir --strict-permissions -d "$LEIHS_HOSTNAME"'
