#!/bin/sh -exu
CHANNEL=$1

git submodule update --init --force leihs
cd leihs
git fetch origin
git submodule foreach --recursive 'git reset --hard HEAD || exit 0'
git reset --hard "origin/${CHANNEL}"
git submodule update --recursive --init --force
