---
leihs_external_hostname: demo.leihs.zhdk.ch

ansible_host: zhdk-leihs-demo.ruby.zhdk.ch
ansible_user: root

leihs_send_mails: No

db_backup_keep_days: 4
db_backup_nigthly_enabled: No
db_backup_on_deploy: No # don't set this to true for first deploy!

database_dump_restore_file_path: '{{inventory_dir}}/leihs/legacy/features/personas/demo.pgbin'

settings_file_path: '{{inventory_dir}}/settings/demo.leihs.zhdk.ch.yml'
