- import_playbook: "{{playbook_dir}}/../../leihs/deploy/stop_play.yml"

- hosts: leihs_server
  vars:
    db_dump_tmpfile: "/tmp/leihs-demo.pgbin"
  tasks:
    - shell: |
        set -eux
        cd /leihs/database
        export PATH=$HOME/.rubies/ruby-{{leihs_database_ruby_version}}/bin:$PATH
        export RAILS_ENV=production
        export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
        ruby -S bundle exec rake db:environment:set
        ruby -S bundle exec rake db:drop db:create
      become: yes
      become_user: "{{leihs_database_user}}"
      name: create and migrate database

    - name: copy DB dump to server
      copy:
        src: "{{playbook_dir}}/../../leihs/legacy/features/personas/demo.pgbin"
        dest: "{{db_dump_tmpfile}}"
        owner: "{{leihs_legacy_user}}"

    - name: restore the DB dump
      shell: |
        set -eux
        cd /leihs/legacy
        export PATH=$HOME/.rubies/ruby-{{leihs_database_ruby_version}}/bin:/usr/lib/postgresql/{{postgres_version}}/bin:$PATH
        export RAILS_ENV=production
        export FILE="{{db_dump_tmpfile}}"
        export LEIHS_SECRET="{{leihs_master_secret}}"
        ruby -S bundle exec rake db:pg:structure_and_data:restore
      become: yes
      become_user: "{{leihs_legacy_user}}"

- import_playbook: "{{playbook_dir}}/../../leihs/deploy/start_play.yml"
