jobs:
  reset_dump:
    name: Reset Dump Demo

    run_when:
      nightly:
        type: cron
        value: '0 2 * * *' # 2am UTC === 1am or 2am in Zurich (Summer/Winter)
        branch_include_match: ^master$
        rerun: true

    context:
      include: cider-ci/tasks/defaults.yml

      tasks:
        deploy:
          exclusive_global_resources:
            "demo.leihs.zhdk.ch": true

          scripts:
            deploy:
              timeout: 30 minutes
              body: |
                ./scripts/reset-dump && echo OK
